spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=QLBanHang;encrypt=true;trustServerCertificate=true
    username: lam
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  thymeleaf:
    cache: false
  mvc:
    hidden-method:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 668463851394-273grt357cptb83mnno2dsvj7rh22kft.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: 2508748359465629
            client-secret: ee3362f823080c8e8e1a75b15fb2e6f5
            scope: email, public_profile
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranlam27052005@gmail.com
    password: wjwj fclg fsho rade
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#recaptcha:
#  site-key: 6LekXxQrAAAAAJFcrIv-LVhw0gFIv8ccu0muDsCL
#  secret-key: 6LekXxQrAAAAAAr-doJEUW8UyTOPxogvbcjhBKDL